# Generated by Django 3.1.7 on 2021-03-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'verbose_name': 'Тудушка', 'verbose_name_plural': 'Тудушки'},
        ),
    ]
