# Generated by Django 3.1.7 on 2021-03-02 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210302_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 8, 55, 5, 747783)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='due_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 8, 55, 5, 747806)),
        ),
    ]
