# Generated by Django 3.1.7 on 2021-03-05 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210302_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 15, 0, 1, 620421)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='due_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 15, 0, 1, 620442)),
        ),
    ]
